# Generated by Django 4.2.6 on 2023-10-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartype",
            old_name="name",
            new_name="model_auto",
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
