# Generated by Django 4.2.6 on 2023-10-25 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_client_phone_alter_dealership_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_paid",
        ),
        migrations.RemoveField(
            model_name="orderquantity",
            name="car_type",
        ),
        migrations.AddField(
            model_name="order",
            name="car",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="store.car",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderquantity",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="orderquantity",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_quantity",
                to="store.order",
            ),
        ),
    ]
